name: Test, Build, and Deploy

on:
  push:
    branches: ["**"]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    # Only run on push if it's not a pull_request event for the same commit
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run tests
        run: go test ./...

  pages:
    needs: test
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build site with June (Docker)
        run: |
          docker build -t june .
          mkdir -p public
          docker run --rm -v ${{ github.workspace }}/examples:/site/examples -v ${{ github.workspace }}/public:/site/public june examples/june.md -o public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages

  release:
    needs: test
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))) || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: Set snapshot flag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
