name: Build and Deploy June Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site with June (Docker)
        run: |
          docker build -t june .
          mkdir -p public
          docker run --rm -v ${{ github.workspace }}/examples:/site/examples -v ${{ github.workspace }}/public:/site/public june examples/june.md -o public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages